server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    security:
      user:
        name: root
        password: root
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
