server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    security:
      user:
        name: root
        password: root

plaza:
  service:
    url: http://localhost:8082/api/v1

application:
  security:
    jwt:
      secret-key: DnkM6Yeq/oVtI4WHmTHqCUSpFZ4eNvPqI7xnsq1upr4=
      expiration: 86400000
      refresh-token:
        expiration: 604800000

appDescription: "Pragma Powerup"
appVersion: "1.0.0"